version: "3.8"

# Common Health Check Properties
x-healthcheck-config: &healthcheck-ref
  interval: 15s
  timeout: 10s
  retries: 100
  start_period: 30s

name: dc-clients-tu
services:
  # ePA client services
  ps-sim:
    image: europe-west3-docker.pkg.dev/gematik-all-infra-prod/epa/ps-sim:latest
    container_name: ps-sim
    restart: 'no'
    healthcheck:
      <<: *healthcheck-ref
      test: "wget -T5 -qO- http://localhost:8081/actuator/health | grep UP || exit 1"
    environment:
      - SPRING_PROFILES_ACTIVE=mock
      - SERVER_PORT=8080
      - MANAGEMENT_SERVER_PORT=8081
      - AUTH_SERVER_HOST=vau-proxy-ps-sim
      - AUTH_SERVER_PORT=8080
      - IDP_SERVER_PROTOCOL=https
      - IDP_SERVER_HOST=idp-test.zentral.idp.splitdns.ti-dienste.de
      #- IDP_SERVER_HOST=idp-ref.app.ti-dienste.de
      - IDP_SERVER_PORT=443
      - IDP_SERVER_PATH=.well-known/openid-configuration
      - VAU_PROXY_HOST=vau-proxy-ps-sim
      - VAU_PROXY_PORT=8080
      - INF_SERVER1_PROTOCOL=https
      - INF_SERVER1_HOST=epa-as-1.test.epa4all.de
      - INF_SERVER1_PORT=443
      - INF_SERVER2_PROTOCOL=https
      - INF_SERVER2_HOST=epa-as-2.test.epa4all.de
      - INF_SERVER2_PORT=443
      - FHIR_SERVER_HOST=vau-proxy-ps-sim
      - FHIR_SERVER_PORT=8080
      - FHIR_SERVER_PATH=epa/medication/api/v1/fhir
      - EML_RENDER_HOST=vau-proxy-ps-sim
      - EML_RENDER_PORT=8080
      - ENTITLEMENT_SERVER_HOST=vau-proxy-ps-sim
      - ENTITLEMENT_SERVER_PORT=8080
      - DOCUMENT_SERVICE_MOCK_CONNECTION_ADDRESS_HOST=vau-proxy-ps-sim
      - DOCUMENT_SERVICE_MOCK_CONNECTION_ADDRESS_PORT=8080
      # public konnektor (with VPN)
      - KONNEKTOR_HOST=ksp.ltuzd.telematik-test
      - KONNEKTOR_PORT=443
      - KONNEKTOR_PROTOCOL=https
      - BASIC_AUTHENTICATION_ENABLED=false
      - BASIC_AUTHENTICATION_USERNAME=user1
      - BASIC_AUTHENTICATION_PASSWORD=SnV?:bTT+mUK
      - KONNEKTOR_CONNECTION_ADDRESS_PATH=kon35
      # artica proxy (with VPN)
      - EPA_PROXY_HOST=10.11.98.80
      - EPA_PROXY_PORT=8080
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:6000,server=y,suspend=n
      #- HTTP_PROXY_HOST=10.11.98.80
      #- HTTP_PROXY_PORT=8080
      #- HTTPS_PROXY_HOST=10.11.98.80
      #- HTTPS_PROXY_PORT=8080
      #- HTTP_NON_PROXY_HOSTS=epa-as-1.dev.epa4all.de|epa-as-2.dev.epa4all.de
    networks:
      - client-network
#    extra_hosts:
#      - "epa-as-1.test.epa4all.de:172.30.19.143"
    ports:
      - "8080:8080"
      - "6000:6000"

  vau-proxy-ps-sim:
    image: europe-west3-docker.pkg.dev/gematik-all-infra-prod/epa/vau-proxy-client:latest
    container_name: vau-proxy-ps-sim
    restart: 'no'
    healthcheck:
      <<: *healthcheck-ref
      test: "wget -T5 -qO- http://localhost:8080/actuator/health | grep UP || exit 1"
    environment:
      - SPRING_PROFILES_ACTIVE=client-tu-and-ru
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:6000,server=y,suspend=n
      - CLIENT_SSL_TRUST_STORE=file:///app/config/root.p12
      - VAU_PROXY_SERVER_URL=https://epa-as-1.test.epa4all.de:443 # IBM as default
      - CLIENT_SSL_ENABLED=false
      - SPRING_CODEC_MAX_IN_MEMORY_SIZE=10MB # due to big HTTP Responses (.e.g eML as PDF)
      # proxy settings for VAU handshake
      - CLIENT_PROXY_ENABLED=true
      - CLIENT_PROXY_URL=10.11.98.80
      - CLIENT_PROXY_PORT=8080
      # proxy settings for gateway
      - SPRING_CLOUD_GATEWAY_HTTPCLIENT_PROXY_HOST=10.11.98.80
      - SPRING_CLOUD_GATEWAY_HTTPCLIENT_PROXY_PORT=8080
      #- SPRING_CLOUD_GATEWAY_HTTPCLIENT_PROXY_HTTPS_SSL_USE_INSECURE_TRUST_MANAGER=true
    networks:
      - client-network
#    extra_hosts:
#      - "epa-as-1.test.epa4all.de:172.30.19.143"
    volumes:
      - ./tiger-proxy/root.p12:/app/config/root.p12
      - ./vau-proxy/application-client-tu-and-ru.yaml:/app/config/application-client-tu-and-ru.yaml
    ports:
      - "6001:6000"

networks:
  client-network:
    name: client-network
